<?php

namespace Chanchito\ChanchitoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HorarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorarioRepository extends EntityRepository
{
}