<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ChanchitoChanchitoBundleEntityUsuarioProxy extends \Chanchito\ChanchitoBundle\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function obtenerNombreCompleto()
    {
        $this->__load();
        return parent::obtenerNombreCompleto();
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setNombres($nombres)
    {
        $this->__load();
        return parent::setNombres($nombres);
    }

    public function getNombres()
    {
        $this->__load();
        return parent::getNombres();
    }

    public function setApellidos($apellidos)
    {
        $this->__load();
        return parent::setApellidos($apellidos);
    }

    public function getApellidos()
    {
        $this->__load();
        return parent::getApellidos();
    }

    public function setCorreo($correo)
    {
        $this->__load();
        return parent::setCorreo($correo);
    }

    public function getCorreo()
    {
        $this->__load();
        return parent::getCorreo();
    }

    public function setFecharegistro($fecharegistro)
    {
        $this->__load();
        return parent::setFecharegistro($fecharegistro);
    }

    public function getFecharegistro()
    {
        $this->__load();
        return parent::getFecharegistro();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setUrlfoto($urlfoto)
    {
        $this->__load();
        return parent::setUrlfoto($urlfoto);
    }

    public function getUrlfoto()
    {
        $this->__load();
        return parent::getUrlfoto();
    }

    public function addAsistencia(\Chanchito\ChanchitoBundle\Entity\Asistencia $asistencias)
    {
        $this->__load();
        return parent::addAsistencia($asistencias);
    }

    public function getAsistencias()
    {
        $this->__load();
        return parent::getAsistencias();
    }

    public function addParametroTardanza(\Chanchito\ChanchitoBundle\Entity\ParametroTardanza $parametrosTardanza)
    {
        $this->__load();
        return parent::addParametroTardanza($parametrosTardanza);
    }

    public function getParametrosTardanza()
    {
        $this->__load();
        return parent::getParametrosTardanza();
    }

    public function setUsuario($usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function setHorario(\Chanchito\ChanchitoBundle\Entity\Horario $horario)
    {
        $this->__load();
        return parent::setHorario($horario);
    }

    public function getHorario()
    {
        $this->__load();
        return parent::getHorario();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'usuario', 'nombres', 'apellidos', 'correo', 'fecharegistro', 'password', 'urlfoto', 'asistencias', 'horario');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}