ChanchitoBundle:
    resource: "@ChanchitoBundle/Resources/config/routing.yml"
    prefix:   /

_admin_param:
    resource: "@ChanchitoBundle/Resources/config/admin_param_routing.yml"
    prefix:   /admin/Param
    
_admin_user:
    resource: "@ChanchitoBundle/Resources/config/admin_user_routing.yml"
    prefix:   /admin/User  
    
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
