security:
  firewalls:     
    secured_area:
      pattern:    ^/
      anonymous:  ~
      form_login:
        login_path:  /login
        check_path:  /check
      logout:
        path:   /logout
        target: /
  access_denied_url: /denegado        
  access_control:  
    - { path: ^/admin    , roles: ROLE_ADMIN }
    - { path: ^/registro , roles: ROLE_USER }
  providers:
    main:
        providers: [user_db,in_memory] 
    in_memory:
        users:
            admin:     { password: d033e22ae348aeb5660fc2140aec35850c4da997, roles: 'ROLE_ADMIN' }
    user_db:
        entity:  {class:  Chanchito\ChanchitoBundle\Entity\Usuario, property: usuario}  
  encoders:
      Symfony\Component\Security\Core\User\User:
          algorithm:  sha1
          iterations: 1
          encode_as_base64: false    
      Chanchito\ChanchitoBundle\Entity\Usuario: sha512
              