security:
  firewalls:
    secured_area:
      pattern:    ^/
      anonymous:  ~
      form_login:
        login_path:  /login
        check_path:  /check
      logout:
        path:   /logout
        target: /
  access_control:  
    - { path: ^/perfil , roles: ROLE_USER }
  providers:
    main:
      entity:    
        class:    Chanchito\ChanchitoBundle\Entity\Usuario
        property: usuario
  encoders:
    Chanchito\ChanchitoBundle\Entity\Usuario: sha512
              