ChanchitoBundle_homepage:
    pattern:  /listadoAsistencia
    defaults: { _controller: ChanchitoBundle:Asistencia:show }

ChanchitoBundle_registro:
    pattern:  /registro
    defaults: { _controller: ChanchitoBundle:Asistencia:new }
    
login:
    pattern:  /login
    defaults: { _controller: ChanchitoBundle:Usuario:login }
    
login_check:
    pattern:  /check  
  
logout: 
    pattern:  /logout  

denegado:
    pattern:  /denegado
    defaults: { _controller: ChanchitoBundle:Usuario:denegado }    
    
admin_homepage:
    pattern:  /admin
    defaults: { _controller: ChanchitoBundle:AdminParam:list  }    