ChanchitoBundle_homepage:
    pattern:  /listadoAsistencia
    defaults: { _controller: ChanchitoBundle:Asistencia:show }

ChanchitoBundle_registro:
    pattern:  /registro
    defaults: { _controller: ChanchitoBundle:Asistencia:new }