parameters:
#    chanchito.example.class: Chanchito\ChanchitoBundle\Example

services:
#    chanchito.example:
#        class: %chanchito.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
